version: "3.9"

services:
  postgres:
    container_name: Database
    image: postgres:latest
    environment:
      POSTGRES_DB: emplehoy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./src/main/resources/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql

  java-app:
    container_name: App
    build:
      context: .
    depends_on:
      - postgres
    restart: on-failure
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/emplehoy
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root


